apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: "catalogue-mtls"
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
  targets:
  - name: "catalogue"
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: "front-end-mtls"
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
  targets:
  - name: "front-end"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "catalogue-mtls"
spec:
  host: "catalogue.user10-sockshop.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
