apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
  - port: 80
    name: http
  type: ClusterIP
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    version: safe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: safe
  template:
    metadata:
      labels:
        app: helloworld
        version: safe
    spec:
      containers:
      - name: helloworld
        image: quay.io/oktaysavdi/istioproject:v1 #Code Repo https://github.com/OktaySavdi/dotnet-example
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
  labels:
    version: risky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: risky
  template:
    metadata:
      labels:
        app: helloworld
        version: risky
    spec:
      containers:
      - name: helloworld
        image: quay.io/oktaysavdi/istioproject:v2 #Code Repo https://github.com/OktaySavdi/dotnet-example
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 80
